### ISSUE TITLE
Error: dequeueTask and enqueueTask no longer supported - Tests fail in IE and Chrome

### ISSUE THREAD

**Issue by ganeshkbhat** [mcfly-io/generator-mcfly-ng2#49]
When running tests I get an error `Error: dequeueTask and enqueueTask no longer supported and will be removed in next major release. Use ....` - Tests fail in IE 11.x.x and Chrome 48.x.xxxx. I have one test each for directive, component, service and they work fine with PhantomJS2. IE 11.x.x in Win 8.1 fails but reverts to PhantomJS2 testing instead.

**Comment by thaiat** [comment]
can you share your project ?

**Comment by ganeshkbhat** [comment]
The error comes from seed project not your karma.conf and gulp. I am launching PhantomJS2 instead of PhantomJS as browser. When I use PhantomJS even chrome passes the tests. I am using win 8.1 and nodejs 5.3.0. The project is a clean template project no additions of code. Directive template tests fails but thats because of input requirements.
[configs.zip](https://github.com/mcfly-io/generator-mcfly-ng2/files/138972/configs.zip)

**Comment by thaiat** [comment]
Warning is normal, this is coming from the fact that angular2 uses angular 2 pollyfill bundle and that it uses deprecated features, nothing to worry about, it will probably be gone with the next release.

In any case it should not make your test fail. If this is the case the issue is elsewhere.
