### ISSUE TITLE
Use Node Modules

### ISSUE THREAD

**Issue by iosonosempreio** [mcfly-io/generator-mcfly-ng2#52]
I know this might be a stupid question, but I cannot find documentation, so:
could someone please tell me how to use modules installed through npm?

Should I link them into the index.html? If I do, then an error is triggered since it is not possible to find the node_modules folder

Thanks

**Comment by iosonosempreio** [comment]
Ok, I understood that the file `vendor.ts` is managing all the packages and that the `webpack.config.js` is configured to tell the former to draw from the `node_modules` folder.

If you want to install Bootstrap, as I did, install [this module ](https://github.com/bline/bootstrap-webpack)and follow its guide.

Still, I do not understand how to import a `style.css` file directly in the `index.html`.

**Comment by thaiat** [comment]
yep just do
```js
require('path_to_your_file/style.css');
```
in boostrap.ts or vendor.ts

**Comment by iosonosempreio** [comment]
Hi @thaiat thank you for your reply! Unfortunately isn't working yet.
I get this error message, in which it tells me that the style.css file is not found. But it is exactly in the same folder where it says it is not.

![screen shot 2016-03-01 at 14 33 10](https://cloud.githubusercontent.com/assets/7115395/13428434/cc34753a-dfba-11e5-97ea-2e9d84f15c44.png)

Please help me out of this!
